name: CLAP_PC
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ffmpeg
  - numpy=1.26.4
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - ipykernel
  - pip:
      - streamlit==1.39.0
      - tensorflow-macos<=2.19.0 ; sys_platform == "darwin"      # (Apple Silicon)
      - tensorflow==2.19.0 ; sys_platform != "darwin"
      - tensorflow-hub==0.16.1
      - torch==2.8.0
      - torchaudio==2.8.0
      - transformers==4.56.0
      - librosa==0.11.0
      - soundfile==0.13.1
      - openai-whisper>=20231117
      - mysql-connector-python==9.1.0
      - plotly==5.24.1
      - scipy<=1.16.1
      - sympy==1.13.3
      - pydub==0.25.1
      - python-dotenv==1.1.1
      - joblib==1.5.1
      - streamlit_image_coordinates==0.4.0
      

    